
#ifndef SHAIRPORT_ANDROID_CONFIG_MK

CONFIG_CUSTOMPIDDIR=yes
CONFIG_OPENSSL=yes
CONFIG_RKTUBE=yes
CONFIG_DNS_SD=yes
CONFIG_TINYSVCMDNS=yes
CONFIG_SOXR=no
CONFIG_AVAHI=no
CONFIG_ALSA=no
CONFIG_SNDIO=no
CONFIG_STDOUT=no
CONFIG_PIPE=no
CONFIG_AO=no
CONFIG_PULSE=no
CONFIG_DUMMY=no

CUSTOM_PID_DIR=/data/tube

#endif
