#!/command/with-contenv sh

if [ "$ENABLE_AVAHI" = "1" ]; then
  echo "Starting dbus-daemon"
  exec s6-notifyoncheck dbus-daemon --system --nofork --nopidfile
else
  echo "Avahi disabled, not starting dbus-daemon"
  exec s6-notifyoncheck sleep infinity
fi
