#!/command/with-contenv sh

if [ "$ENABLE_AVAHI" = "1" ]; then
  rm -rf /var/run/dbus.pid
  echo "Starting dbus"
  exec dbus-daemon --system --nofork
else
  echo "Avahi disabled, not starting dbus-daemon"
  exec sleep infinity
fi
