name: macos classic, CoreAudio, BREW

on:
  workflow_dispatch:
  push:
    branches: [ "development" ]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v6.0.2
    - name: Install Dependencies
      run: |
        brew install automake autoconf libtool pkg-config
        brew install popt libconfig openssl@3

    - name: Configure
      run: |
        export PKG_CONFIG_PATH="$(brew --prefix openssl@3)/lib/pkgconfig${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}"
        autoreconf -fi
        ./configure --with-stdout --with-dns_sd --with-ssl=openssl

    - name: Make
      run: make
